# Config file for automatic testing at travis-ci.org

language: python

python: 3.5

# Use container based infrastructure
sudo: false

env:
  matrix:
    - TOXENV=flake8

    - TOXENV=py35-dj111-cms35
    - TOXENV=py35-dj111-cms34
    - TOXENV=py34-dj111-cms35
    - TOXENV=py34-dj111-cms34
    - TOXENV=py27-dj111-cms35
    - TOXENV=py27-dj111-cms34

    - TOXENV=py35-dj110-cms35
    - TOXENV=py35-dj110-cms34
    - TOXENV=py34-dj110-cms35
    - TOXENV=py34-dj110-cms34
    - TOXENV=py27-dj110-cms35
    - TOXENV=py27-dj110-cms34

    - TOXENV=py35-dj19-cms34
    - TOXENV=py35-dj19-cms33
    - TOXENV=py35-dj19-cms32
    - TOXENV=py34-dj19-cms34
    - TOXENV=py34-dj19-cms33
    - TOXENV=py34-dj19-cms32
    - TOXENV=py27-dj19-cms34
    - TOXENV=py27-dj19-cms33
    - TOXENV=py27-dj19-cms32

    - TOXENV=py35-dj18-cms34
    - TOXENV=py35-dj18-cms33
    - TOXENV=py35-dj18-cms32
    - TOXENV=py34-dj18-cms34
    - TOXENV=py34-dj18-cms33
    - TOXENV=py34-dj18-cms32
    - TOXENV=py27-dj18-cms34
    - TOXENV=py27-dj18-cms33
    - TOXENV=py27-dj18-cms32

cache:
  directories:
    - $HOME/.wheelhouse

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV

after_script:
  - codeclimate < tests/coverage/**/lcov.info

after_success: coveralls

notifications:
  webhooks: http://addons.us-iad-rs.aldryn.io/en/travis-endpoint/
